sudo: required

services:
  - docker

env:
  global:
    - PULL_IMAGES=true
    - PUSH_IMAGES=true

before_script:
  - docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

script:
  - ./build-all.sh
